fruits_fruits:
    resource: "@FruitsBundle/Resources/config/routing/fruits.yml"
    prefix:   /fruits

fruits_user:
    resource: "@FruitsBundle/Resources/config/routing/user.yml"
    prefix:   /user