fruit_index:
    path:     /
    defaults: { _controller: "FruitsBundle:Fruits:getAll" }
    methods:  GET

fruit_show:
    path:     /show/{id}
    defaults: { _controller: "FruitsBundle:Fruits:getOne" }
    methods:  GET

fruit_new:
    path:     /new
    defaults: { _controller: "FruitsBundle:Fruits:new" }
    methods:  POST

fruit_edit:
    path:     /edit/{id}
    defaults: { _controller: "FruitsBundle:Fruits:edit" }
    methods:  PUT

fruit_delete:
    path:     /delete/{id}
    defaults: { _controller: "FruitsBundle:Fruits:delete" }
    methods:  DELETE

