fruits_index:
    path:     /
    defaults: { _controller: "FruitsBundle:Fruits:index" }
    methods:  GET

fruits_show:
    path:     /{id}/show
    defaults: { _controller: "FruitsBundle:Fruits:show" }
    methods:  GET

fruits_new:
    path:     /new
    defaults: { _controller: "FruitsBundle:Fruits:new" }
    methods:  [GET, POST]

fruits_edit:
    path:     /{id}/edit
    defaults: { _controller: "FruitsBundle:Fruits:edit" }
    methods:  [GET, POST]

fruits_delete:
    path:     /{id}/delete
    defaults: { _controller: "FruitsBundle:Fruits:delete" }
    methods:  DELETE
